var express = require('express');
var http = require('http');
var socketio = require('socket.io');

var app = express();
var server = http.Server(app);
var io = socketio(server);

var host = process.env.IP || "0.0.0.0";
var port = process.env.PORT || 8080;

var squares = {};

app.use('/static', express.static(__dirname + '/public'));

app.get('/', function (req, res) {
	res.sendFile(__dirname + '/public/html/index.html');
});

server.listen(port, host, function() {
	console.log("Listening on 8080");
});

var map = [
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'],                      collidable: false, bgIndex: 0            }, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}],
	[{bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}, {bgSprites: ['grass'], fgSprites: ['rock'], collidable: false, bgIndex: 0, fgIndex: 0}]
];

/*
var map = [
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass'	                                         	  , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass'	                               , collidable: false, bgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]],
	[[{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}], [{background: 'grass', foreground: 'rock', collidable: false, bgIndex: 0, fgIndex: 0}]]
];*/

io.on('connection', function(socket) {
	socket.emit('mapData', map);
});